name: 'WordPress Plugin Deploy'
description: 'Deploy to the WordPress Plugin Repository'
author: '10up'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  version:
    description: 'Version number of plugin'
branding:
  icon: 'upload-cloud'
  color: 'blue'
